server:
   applicationConnectors:
   - type: http
     port: 9000
   adminConnectors:
   - type: http
     port: 9001

mySqlConfig:
  url: jdbc:h2:mem:regression_user_db;DB_CLOSE_DELAY=-1
  driverClass: org.h2.Driver
  #url: jdbc:mysql://localhost:3306/regression_user_db?useSSL=false
  #driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  properties:
    charSet: UTF-8

